import {
    // TrendingUpIcon,
    // DollarSignIcon,
    BarChartIcon,
    
  } from "@radix-ui/react-icons"; // Import appropriate icons
  
  import { BentoCard, BentoGrid } from "@/components/ui/bento-grid";
import { ChartNoAxesCombined } from "lucide-react";
import { HiCurrencyDollar } from "react-icons/hi";
  
  
  const metrics = [
    {
      Icon: ChartNoAxesCombined,
      name: "Earnings Per Share (EPS)",
      description: "EPS is a company's profit divided by its number of outstanding shares.",
      href: "/", // Add href if needed
      cta: "Learn more", // Add cta if needed
      background: null, // Set to null or a suitable background if needed
    },
    {
      Icon: HiCurrencyDollar,
      name: "Revenue",
      description: "Revenue is the total amount of money generated by the sale of goods or services.",
      href: "/", // Add href if needed
      cta: "Learn more", // Add cta if needed
      background: null, // Set to null or a suitable background if needed
    },
    {
      Icon: BarChartIcon,
      name: "Return on Equity (ROE)",
      description: "ROE measures a corporation's profitability by revealing how much profit a company generates with the money shareholders have invested.",
      href: "/", // Add href if needed
      cta: "Learn more", // Add cta if needed
      background: null, // Set to null or a suitable background if needed
    },
  ];
  
  export default async function BentoPrediction() {
    return (
      <div className="flex justify-center items-center h-3-4">
        <div className="w-3/4 bg-muted/20 shadow-lg rounded-lg p-8">
          <h2 className="text-3xl font-bold text-center mb-4 bg-gradient-to-b from-violet-500 to-purple-600 bg-clip-text text-transparent">Stock Fundamental Data Forecasting</h2>
          <p className="text-center mb-8">
            <span className="font-extrabold">Quanta</span> uses three key metrics to predict stock performance of any company.
          </p>
          <BentoGrid className="flex gap-6">
            {metrics.map((metric) => (
              <BentoCard
                key={metric.name}
                className="flex flex-col items-center p-4 rounded-lg shadow-md"
                background={metric.background}
                Icon={metric.Icon}
                name={metric.name}
                description={metric.description}
                href={metric.href}
                cta={metric.cta}
              />
            ))}
          </BentoGrid>
        </div>
      </div>
    );
  }